export const CAT6_SALE_PRODUCTS = [
  "0.50 Meters CAT6 Patch Cable Soild with Connectors",
  "1.00 Meters CAT6 Patch Cable Soild with Connectors",
  "1.5 Meters CAT6 Patch Cord",
  "15 Meter CAT6 Patch Cord",
  "2.00 Meters CAT6 Patch Cable Soild with Connectors",
  "2.00 Meters CAT6 Patch Cord",
  "3.00 Meters CAT6 Patch Cable Soild with Connectors",
  "4P 23 AWG. CAT 6 UTP SHLD LSZH CABLE",
  "Cable Armoured CAT 6 UTP",
  "CAT 6 23 AWG CABLES",
  "Cat 6 23 AWG SFTP ARMOURED",
  "Cat 6 23 AWG SFTP ARMOURED (COIL)",
  "CAT 6 23 AWG STP CABLE",
  "CAT 6 23 AWG UTP CABLE",
  "CAT 6 23 AWG UTP CABLE (MTR)",
  "CAT 6 24 AWG DOUBLE SHEATHED CABLE",
  "CAT 6 24 AWG STP CABLES",
  "CAT 6 24 AWG UTP CABLE",
  "CAT 6 24 AWG UTP CABLES",
  "Cat-6 23 AWG (0.550+/-0.005) SFTP Armoured",
  "Cat-6 23 AWG UTP Cable ARMOURED",
  "Cat-6 23AWG UTP Cable",
  "CAT-6 24 AWG STP CABLE",
  "CAT-6 24 AWG STP CABLE (COIL)",
  "CAT-6 24 AWG UTP CABLE ARMOURED",
  "CAT-6 24 AWG UTP Cables (COIL)",
  "CAT5 24 AWG UTP CABLE",
  "CAT5E 24 AWG UTP CABLES",
  "CAT5E 24AWG UTP Cable",
  "CAT6 23 AWG Cable",
  "CAT6 23 AWG SFTP Cable(M)",
  "CAT6 23 AWG SFTP Cables",
  "Cat6 23Awg Double sheathed sftp cable (COIL)",
  "Cat6 23Awg Double sheathed UTP Cable",
  "CAT6 23AWG SFTP Cable",
  "CAT6 23AWG UTP Indoor Networking Cable",
  "CAT6 24 AWG Cable",
  "CAT6 24 AWG Cables",
  "Cat6 24 AWG Double Sheathed Outdoor Cable",
  "Cat6 24 AWG Double Sheathed Outdoor Networking Cable",
  "CAT6 24 AWG SFTP",
  "CAT6 24 AWG SFTP Cable",
  "CAT6 24 AWG SFTP CABLES",
  "CAT6 24 AWG SFTP DOUBLE SHEATHED OUTDOOR",
  "CAT6 24 AWG UTP DOUBLE SHEATHED CABLES",
  "CAT6 24AWG Copper UTP Patch Cable with RJ45 connectors 1 MTR",
  "CAT6 24AWG Copper UTP Patch Cable with RJ45 connectors 10 MTR",
  "CAT6 24AWG Copper UTP Patch Cable with RJ45 connectors 3 MTR",
  "Cat6 24Awg Double sheathed outdoor networking cable",
  "CAT6 24AWG SFTP DOUBLE SHEATHED",
  "CAT6 24AWG UTP DOUBLE SHEATHED CABLES ( COIL)",
  "CAT6 24AWG UTP Indoor Networking Cable",
  "CAT6 24AWG UTP Patch Cable with RJ45 connectors 1 MTR",
  "CAT6 24AWG UTP Patch Cable with RJ45 connectors 10 MTR",
  "CAT6 24AWG UTP Patch Cable with RJ45 connectors 15 MTR",
  "CAT6 CABLES",
  "CAT6 PATCH CABLE WITH RJ45 CONNECTORS 0.5MTRS",
  "CAT6 UTP 24AWG Cable",
  "CAT6 UTP 24AWG DOUBLE SHEATHED OUTDOOR LAN CABLE 100MTRS",
  "CAT6 UTP 24AWG Indoor Networking Cable",
  "CAT6 UTP AWG Cable",
  "Notofire CAT6 UTP 23 AWG 305 mm (Gray)",
  "Notofire CAT6 UTP 23 AWG 305 mm (Purple)",
  "Notofire CAT6 UTP 23 AWG 305 mm (Yellow)",
  "Notofire CAT6 UTP 24 AWG 305 m (Blue)",
  "patch cable with connector Length 10mtr",
  "patch cable with connector Length 15mtrs",
  "patch cable with connector Length 5mtr",
  "SY-CAT6 -SFTP 305M Cable(M)",
  "SY-CAT6 -UTP 305M",
  "Other",
] as const;
