/** Dropdown options extracted from Noto_CAT-6 Plant P&L_V1.xlsx */

export const CAT6_CUSTOMERS = [
  "A Secure Systems",
  "Aaa Systems and Peripherals",
  "ADITYA ENTERPRISES",
  "Aditya Technology Partners",
  "AGM IT NETWORK PRIVATE LIMITED",
  "Anu Enterprises",
  "ANUPAM ELECTRICALS",
  "Ark Enterprises",
  "Arnav Tecno Solutions",
  "ASR Enterprises",
  "Ayansh Infocom Private Limited",
  "Bharat Cable Industries",
  "Black Copper India Private Limited",
  "Chrome Infra",
  "Dacam Systems Private Limited",
  "Dee Kay Systems",
  "Digamber Telecom",
  "Digital Elements",
  "Dron Edge India Private Limited",
  "Epsillon Cables Private Limited",
  "Eurovison Technologies",
  "Garuda Trades and Services",
  "Gd Infotech",
  "Geep Polymers India Private Limited",
  "Genius Engineering Solutions",
  "Glow Right Electric Source Private Limited",
  "Go Ip Global Services Private Limited",
  "Godavari Enterprises",
  "Green Cube Technologies Pvt.Ltd",
  "Green's Way Technology",
  "Hamsa India",
  "Harshita Electric Corporation",
  "HI FOCUS ELECTRONICS INDIA PRIVATE LIMITED",
  "I3 Secnsol Private Limited",
  "Integrated Fire Protection Pvt. Ltd.",
  "J K Exim Private Limited",
  "Jai Enterprises",
  "Jp Technologies",
  "Kakatiya Technologies",
  "KHANDELWAL ELECTRICALS",
  "Khushi Electrical Solutions",
  "King Tech Solutions",
  "Laxmi Security Systems and Electricals",
  "M/s Micro Systems",
  "M/s Mx Electronics & Telecommunications",
  "M/s Nectar Infotech",
  "M/s Roop Krishna Enterprises",
  "M/s Samriddhi Automations Pvt Ltd",
  "M/s Samriddhi Automations Pvt Ltd (Haryana)",
  "M/S Samriddhi Automations Pvt. Ltd (Haridwar)",
  "M/S SUMIRATAN IT SOLUTIONS",
  "M/S VISION ELECTRONICS",
  "M/s.TECHNO MAC ENGINEERS",
  "Maruthi Computer Services",
  "Maruthi It Services",
  "MASH INTERTECH PRIVATE LIMITED",
  "Matrix Technologies",
  "Meenucab Enterprises",
  "Metro Wireless",
  "Mk Security Solutions",
  "Modern Technologies",
  "Mp Technologies",
  "Naitik Infotex",
  "NATIONAL CIRCUITS AND COMPONENTS ELECTRONICS INDIA",
  "Nav Yug Engineering",
  "New Tec Communication",
  "Nysha Mobility Tech Private Limited (RM)",
  "P J Technologies",
  "P.O.No.: 95255437100608 dated 09-SEP-25",
  "Peak Star Networks",
  "Pi Square Cables Pvt. Ltd",
  "PO: 511687737496633 Dt 30-07-2025 (GEM)",
  "QLO Networks Private Limited",
  "R J INDUSTRIAL CORPORATION",
  "R.J. INDUSTRIAL CORPORATION PRIVATE LIMITED",
  "Reliable Fire and Security Systems",
  "Reliable Security Zone",
  "Rey Techno Solutions",
  "Rithvik Safe Line Technologies Pvt Ltd",
  "SAPPHIRE INFOMATIQUE",
  "Savit Broad Band Networks",
  "Savitha Enterprises",
  "Sdr Tech Solutions",
  "Shiridi Sai Peripheral Systems",
  "Shri Nath Security Solutions",
  "Sun Computer Hub",
  "Sunnet Solutions Pvt Limited",
  "Supaasi Solar Auto Tracking Systems Private Limited",
  "Target Security & Automation",
  "THDC INDIA LTD",
  "Trisent Production Private Limited",
  "Ts Infra Engineers Private Limited",
  "V Square Security Systems",
  "Vasram Enterprises",
  "Vinayaka Global Services Pvt Ltd",
  "Vishal Electronics",
  "Vision Technologies",
  "Wirelux Cables Private Limited",
  "Yernest Compactivity",
  "Other",
] as const;
