/** Dropdown options extracted from Noto_CAT-6 Plant P&L_V1.xlsx */

export const CAT6_CUSTOMERS = [
  "A Secure Systems",
  "Aaa Systems and Peripherals",
  "ADITYA ENTERPRISES",
  "Aditya Technology Partners",
  "AGM IT NETWORK PRIVATE LIMITED",
  "Anu Enterprises",
  "ANUPAM ELECTRICALS",
  "Ark Enterprises",
  "Arnav Tecno Solutions",
  "ASR Enterprises",
  "Ayansh Infocom Private Limited",
  "Bharat Cable Industries",
  "Black Copper India Private Limited",
  "Chrome Infra",
  "Dacam Systems Private Limited",
  "Dee Kay Systems",
  "Digamber Telecom",
  "Digital Elements",
  "Dron Edge India Private Limited",
  "Epsillon Cables Private Limited",
  "Eurovison Technologies",
  "Garuda Trades and Services",
  "Gd Infotech",
  "Geep Polymers India Private Limited",
  "Genius Engineering Solutions",
  "Glow Right Electric Source Private Limited",
  "Go Ip Global Services Private Limited",
  "Godavari Enterprises",
  "Green Cube Technologies Pvt.Ltd",
  "Green's Way Technology",
  "Hamsa India",
  "Harshita Electric Corporation",
  "HI FOCUS ELECTRONICS INDIA PRIVATE LIMITED",
  "I3 Secnsol Private Limited",
  "Integrated Fire Protection Pvt. Ltd.",
  "J K Exim Private Limited",
  "Jai Enterprises",
  "Jp Technologies",
  "Kakatiya Technologies",
  "KHANDELWAL ELECTRICALS",
  "Khushi Electrical Solutions",
  "King Tech Solutions",
  "Laxmi Security Systems and Electricals",
  "M/s Micro Systems",
  "M/s Mx Electronics & Telecommunications",
  "M/s Nectar Infotech",
  "M/s Roop Krishna Enterprises",
  "M/s Samriddhi Automations Pvt Ltd",
  "M/s Samriddhi Automations Pvt Ltd (Haryana)",
  "M/S Samriddhi Automations Pvt. Ltd (Haridwar)",
  "M/S SUMIRATAN IT SOLUTIONS",
  "M/S VISION ELECTRONICS",
  "M/s.TECHNO MAC ENGINEERS",
  "Maruthi Computer Services",
  "Maruthi It Services",
  "MASH INTERTECH PRIVATE LIMITED",
  "Matrix Technologies",
  "Meenucab Enterprises",
  "Metro Wireless",
  "Mk Security Solutions",
  "Modern Technologies",
  "Mp Technologies",
  "Naitik Infotex",
  "NATIONAL CIRCUITS AND COMPONENTS ELECTRONICS INDIA",
  "Nav Yug Engineering",
  "New Tec Communication",
  "Nysha Mobility Tech Private Limited (RM)",
  "P J Technologies",
  "P.O.No.: 95255437100608 dated 09-SEP-25",
  "Peak Star Networks",
  "Pi Square Cables Pvt. Ltd",
  "PO: 511687737496633 Dt 30-07-2025 (GEM)",
  "QLO Networks Private Limited",
  "R J INDUSTRIAL CORPORATION",
  "R.J. INDUSTRIAL CORPORATION PRIVATE LIMITED",
  "Reliable Fire and Security Systems",
  "Reliable Security Zone",
  "Rey Techno Solutions",
  "Rithvik Safe Line Technologies Pvt Ltd",
  "SAPPHIRE INFOMATIQUE",
  "Savit Broad Band Networks",
  "Savitha Enterprises",
  "Sdr Tech Solutions",
  "Shiridi Sai Peripheral Systems",
  "Shri Nath Security Solutions",
  "Sun Computer Hub",
  "Sunnet Solutions Pvt Limited",
  "Supaasi Solar Auto Tracking Systems Private Limited",
  "Target Security & Automation",
  "THDC INDIA LTD",
  "Trisent Production Private Limited",
  "Ts Infra Engineers Private Limited",
  "V Square Security Systems",
  "Vasram Enterprises",
  "Vinayaka Global Services Pvt Ltd",
  "Vishal Electronics",
  "Vision Technologies",
  "Wirelux Cables Private Limited",
  "Yernest Compactivity",
] as const;

export const CAT6_SALE_PRODUCTS = [
  "0.50 Meters CAT6 Patch Cable Soild with Connectors",
  "1.00 Meters CAT6 Patch Cable Soild with Connectors",
  "1.5 Meters CAT6 Patch Cord",
  "15 Meter CAT6 Patch Cord",
  "2.00 Meters CAT6 Patch Cable Soild with Connectors",
  "2.00 Meters CAT6 Patch Cord",
  "3.00 Meters CAT6 Patch Cable Soild with Connectors",
  "4P 23 AWG. CAT 6 UTP SHLD LSZH CABLE",
  "Cable Armoured CAT 6 UTP",
  "CAT 6 23 AWG CABLES",
  "Cat 6 23 AWG SFTP ARMOURED",
  "Cat 6 23 AWG SFTP ARMOURED (COIL)",
  "CAT 6 23 AWG STP CABLE",
  "CAT 6 23 AWG UTP CABLE",
  "CAT 6 23 AWG UTP CABLE (MTR)",
  "CAT 6 24 AWG DOUBLE SHEATHED CABLE",
  "CAT 6 24 AWG STP CABLES",
  "CAT 6 24 AWG UTP CABLE",
  "CAT 6 24 AWG UTP CABLES",
  "Cat-6 23 AWG (0.550+/-0.005) SFTP Armoured",
  "Cat-6 23 AWG UTP Cable ARMOURED",
  "Cat-6 23AWG UTP Cable",
  "CAT-6 24 AWG STP CABLE",
  "CAT-6 24 AWG STP CABLE (COIL)",
  "CAT-6 24 AWG UTP CABLE ARMOURED",
  "CAT-6 24 AWG UTP Cables (COIL)",
  "CAT5 24 AWG UTP CABLE",
  "CAT5E 24 AWG UTP CABLES",
  "CAT5E 24AWG UTP Cable",
  "CAT6 23 AWG Cable",
  "CAT6 23 AWG SFTP Cable(M)",
  "CAT6 23 AWG SFTP Cables",
  "Cat6 23Awg Double sheathed sftp cable (COIL)",
  "Cat6 23Awg Double sheathed UTP Cable",
  "CAT6 23AWG SFTP Cable",
  "CAT6 23AWG UTP Indoor Networking Cable",
  "CAT6 24 AWG Cable",
  "CAT6 24 AWG Cables",
  "Cat6 24 AWG Double Sheathed Outdoor Cable",
  "Cat6 24 AWG Double Sheathed Outdoor Networking Cable",
  "CAT6 24 AWG SFTP",
  "CAT6 24 AWG SFTP Cable",
  "CAT6 24 AWG SFTP CABLES",
  "CAT6 24 AWG SFTP DOUBLE SHEATHED OUTDOOR",
  "CAT6 24 AWG UTP DOUBLE SHEATHED CABLES",
  "CAT6 24AWG Copper UTP Patch Cable with RJ45 connectors 1 MTR",
  "CAT6 24AWG Copper UTP Patch Cable with RJ45 connectors 10 MTR",
  "CAT6 24AWG Copper UTP Patch Cable with RJ45 connectors 3 MTR",
  "Cat6 24Awg Double sheathed outdoor networking cable",
  "CAT6 24AWG SFTP DOUBLE SHEATHED",
  "CAT6 24AWG UTP DOUBLE SHEATHED CABLES ( COIL)",
  "CAT6 24AWG UTP Indoor Networking Cable",
  "CAT6 24AWG UTP Patch Cable with RJ45 connectors 1 MTR",
  "CAT6 24AWG UTP Patch Cable with RJ45 connectors 10 MTR",
  "CAT6 24AWG UTP Patch Cable with RJ45 connectors 15 MTR",
  "CAT6 CABLES",
  "CAT6 PATCH CABLE WITH RJ45 CONNECTORS 0.5MTRS",
  "CAT6 UTP 24AWG Cable",
  "CAT6 UTP 24AWG DOUBLE SHEATHED OUTDOOR LAN CABLE 100MTRS",
  "CAT6 UTP 24AWG Indoor Networking Cable",
  "CAT6 UTP AWG Cable",
  "Notofire CAT6 UTP 23 AWG 305 mm (Gray)",
  "Notofire CAT6 UTP 23 AWG 305 mm (Purple)",
  "Notofire CAT6 UTP 23 AWG 305 mm (Yellow)",
  "Notofire CAT6 UTP 24 AWG 305 m (Blue)",
  "patch cable with connector Length 10mtr",
  "patch cable with connector Length 15mtrs",
  "patch cable with connector Length 5mtr",
  "SY-CAT6 -SFTP 305M Cable(M)",
  "SY-CAT6 -UTP 305M",
  "Other",
] as const;

export const CAT6_SUPPLIERS = [
  "3r Polymers Private Limited",
  "AGGARWAL INSULATION Co.",
  "AMAR SHYAM PACKAGING",
  "BELLS INSULATIONS PVT. LTD.",
  "BLS POLYMERS LIMITED",
  "Cablemac Automations India Pvt. Ltd",
  "CROWN TRADING CO.",
  "HYCOUNT CABLES PRIVATE LIMITED",
  "L.R. PACKAGING INDUSTRIES",
  "M/s Goel Packers",
  "Metatech Ccr Private Limited",
  "METATECH WIRE AND CABLES",
  "P C LAMINATIONS",
  "Paramhans Wires Private Limited",
  "Perfect Metals",
  "R J INDUSTRIAL CORPORATION",
  "RAYCOR ELECTROMECH",
  "Sag Polymers Private Limited",
  "Singhal Print Pack",
  "TAKKAR INDUSTRIES",
  "TAKKAR POLYCHEM PRIVATE LIMITED",
  "Tirupati Plastics",
  "TOTAL AMOUNT",
  "Wirelux Cables Private Limited",
  "WIRELUX CABLES PRIVATE LTD",
  "YATHARTH METATECH PRIVATE LIMITED",
] as const;

export const CAT6_PURCHASE_GOODS = [
  "1.5 Meters CAT6 Patch Cord",
  "10 Meters CAT6 Patch Cord",
  "15 Meter CAT6 Patch Cord",
  "15.00 Meters CAT6 Patch Cable Soild with Connectors",
  "2.00 Meters CAT6 Patch Cord",
  "20 Meters CAT6 Patch Cord",
  "30 Meters CAT6 Patch Cord",
  "5 Meters CAT6 Patch Cord",
  "ALU",
  "Aluminium Wire",
  "BOXES",
  "CAT6 PATCH CABLE WITH RJ45 CONNECTORS 0.5MTRS",
  "COPPER",
  "Copper Wire",
  "Copper Wire Rod 8mm",
  "Corrugated Box",
  "DHAGA",
  "HDPE Compound",
  "IN-PVC",
  "INSU",
  "INSU & OUT",
  "LDPE COMPOUND",
  "MASTER BATCH",
  "Masterbatch Grey",
  "MDPE Compound",
  "OT-PVC",
  "PHLOGOPITE_MICA",
  "PLASTIC CRATE",
  "Plastic Granuals",
  "POLYESTER FILM PANCAKES",
  "POLYESTER FILM TAPE",
  "POLYESTER TAPE",
  "Polyster Yarn",
  "PVC Compound",
  "PVC Master Batch",
  "Spool",
  "SPOOL",
  "TAPE",
  "XL_ZHFR",
] as const;

export const CAT6_STOCK_ITEMS = [
  "ARMOURED CAT 6 23 AWG SFTP CABLE 300 MTR",
  "CAT 6 23AWG SFTP DOUBLE SHIELD CABLE - 300 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 0.5 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 1.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 1.5 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 10.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 15.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 2.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 20.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 3.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 30.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 5.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 7.0 MTR",
  "INDOOR CAT 6 23AWG UTP NETWORKING CABLE - 100 MTR",
  "INDOOR CAT 6 23AWG UTP NETWORKING CABLE - 305 MTR",
  "INDOOR CAT 6 24AWG UTP NETWORKING CABLE - 100 MTR",
  "INDOOR CAT 6 24AWG UTP NETWORKING CABLE - 305 MTR",
  "OUTDOOR CAT 6 24AWG DOUBLE SHELD CABLE - 300 MTR",
] as const;

export const CAT6_PETTY_NATURES = [
  "CONSUMABLE EXP.",
  "CONSUMABLE EXPS",
  "CONSUMABLE ITEM",
  "Consumable Items - ATC",
  "CONVEYANCE EXPENSES",
  "ELECTRIC & MAINTENANCE",
  "ELECTRICAL & MAINT. EXP.",
  "FREIGHT & CARTAGE",
  "HOUSE ALLOWANCE",
  "HOUSE ALLOWENCE",
  "INCENTIVE SUNDAY",
  "MEDICAL EXPENSE",
  "PRINTING & STATIONERY",
  "PRINTING & STATIONERY EXP.",
  "PRODUCTION",
  "PRODUCTION EXP.",
  "PRODUCTION EXPENSE",
  "PRODUCTION EXPS",
  "Repair & Maint. Exp - ATC",
  "REPAIR & MAINTENANCE",
  "SALARY & WAGES",
  "STAFF WELFARE",
  "Staff Welfare Exp - ATC",
  "VEHICLE RUNNING",
  "WORKER FOOD ALLOWENCE",
  "WORKER FOODS ALLOWENCE",
] as const;

export const CAT6_PETTY_PERSONS = [
  "ANUJ",
  "DEEPAK RAJ",
  "ISWAR",
  "KISHOR JI",
  "MANISH",
  "NAFEES JI",
  "PRADEEP JI",
  "ROHIT",
  "SHUBHAM",
  "SHUKLA JI",
  "SHUKLA SIR",
  "TULSHI JI",
  "TULSI SIR",
  "VIPIN",
] as const;

export const CAT6_PETTY_LOCATIONS = [
  "ATC BHAGWANPUR",
] as const;

export const CAT6_PETTY_CHECKED_BY = [
  "ANUJ",
  "GAURAV",
  "MANISH",
  "SANDESH",
  "VIPIN",
] as const;

export const CAT6_PETTY_APPROVED_BY = [
  "ASHOK SIR",
  "SHUKLA JI",
] as const;

