export const CAT6_STOCK_ITEMS = [
  "ARMOURED CAT 6 23 AWG SFTP CABLE 300 MTR",
  "CAT 6 23AWG SFTP DOUBLE SHIELD CABLE - 300 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 0.5 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 1.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 1.5 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 10.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 15.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 2.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 20.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 3.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 30.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 5.0 MTR",
  "CAT6 PATCH CABLE WITH RJ45 - 7.0 MTR",
  "INDOOR CAT 6 23AWG UTP NETWORKING CABLE - 100 MTR",
  "INDOOR CAT 6 23AWG UTP NETWORKING CABLE - 305 MTR",
  "INDOOR CAT 6 24AWG UTP NETWORKING CABLE - 100 MTR",
  "INDOOR CAT 6 24AWG UTP NETWORKING CABLE - 305 MTR",
  "OUTDOOR CAT 6 24AWG DOUBLE SHELD CABLE - 300 MTR",
  "Other",
] as const;

export const CAT6_PETTY_NATURES = [
  "CONSUMABLE EXP.",
  "CONSUMABLE EXPS",
  "CONSUMABLE ITEM",
  "Consumable Items - ATC",
  "CONVEYANCE EXPENSES",
  "ELECTRIC & MAINTENANCE",
  "ELECTRICAL & MAINT. EXP.",
  "FREIGHT & CARTAGE",
  "HOUSE ALLOWANCE",
  "HOUSE ALLOWENCE",
  "INCENTIVE SUNDAY",
  "MEDICAL EXPENSE",
  "PRINTING & STATIONERY",
  "PRINTING & STATIONERY EXP.",
  "PRODUCTION",
  "PRODUCTION EXP.",
  "PRODUCTION EXPENSE",
  "PRODUCTION EXPS",
  "Repair & Maint. Exp - ATC",
  "REPAIR & MAINTENANCE",
  "SALARY & WAGES",
  "STAFF WELFARE",
  "Staff Welfare Exp - ATC",
  "VEHICLE RUNNING",
  "WORKER FOOD ALLOWENCE",
  "WORKER FOODS ALLOWENCE",
  "Other",
] as const;

export const CAT6_PETTY_PERSONS = [
  "ANUJ",
  "DEEPAK RAJ",
  "ISWAR",
  "KISHOR JI",
  "MANISH",
  "NAFEES JI",
  "PRADEEP JI",
  "ROHIT",
  "SHUBHAM",
  "SHUKLA JI",
  "SHUKLA SIR",
  "TULSHI JI",
  "TULSI SIR",
  "VIPIN",
  "Other",
] as const;

export const CAT6_PETTY_LOCATIONS = [
  "ATC BHAGWANPUR",
  "Other",
] as const;

export const CAT6_PETTY_CHECKED_BY = [
  "ANUJ",
  "GAURAV",
  "MANISH",
  "SANDESH",
  "VIPIN",
  "Other",
] as const;

export const CAT6_PETTY_APPROVED_BY = [
  "ASHOK SIR",
  "SHUKLA JI",
  "Other",
] as const;
