export const CAT6_SUPPLIERS = [
  "3r Polymers Private Limited",
  "AGGARWAL INSULATION Co.",
  "AMAR SHYAM PACKAGING",
  "BELLS INSULATIONS PVT. LTD.",
  "Bhumi InterNational",
  "BLS POLYMERS LIMITED",
  "Cablemac Automations India Pvt. Ltd",
  "CROWN TRADING CO.",
  "HYCOUNT CABLES PRIVATE LIMITED",
  "L.R. PACKAGING INDUSTRIES",
  "M/s Goel Packers",
  "Metatech Ccr Private Limited",
  "METATECH WIRE AND CABLES",
  "Mobec Innovation Pvt Ltd",
  "P C LAMINATIONS",
  "Paramhans Wires Private Limited",
  "Perfect Metals",
  "R J INDUSTRIAL CORPORATION",
  "RAYCOR ELECTROMECH",
  "Sag Polymers Private Limited",
  "Singhal Print Pack",
  "TAKKAR INDUSTRIES",
  "TAKKAR POLYCHEM PRIVATE LIMITED",
  "Tirupati Plastics",
  "TOTAL AMOUNT",
  "Wirelux Cables Private Limited",
  "WIRELUX CABLES PRIVATE LTD",
  "YATHARTH METATECH PRIVATE LIMITED",
  "Other",
] as const;

export const CAT6_PURCHASE_GOODS = [
  "1.5 Meters CAT6 Patch Cord",
  "10 Meters CAT6 Patch Cord",
  "15 Meter CAT6 Patch Cord",
  "15.00 Meters CAT6 Patch Cable Soild with Connectors",
  "2.00 Meters CAT6 Patch Cord",
  "20 Meters CAT6 Patch Cord",
  "30 Meters CAT6 Patch Cord",
  "5 Meters CAT6 Patch Cord",
  "ALU",
  "Aluminium Wire",
  "BOXES",
  "CAT6 PATCH CABLE WITH RJ45 CONNECTORS 0.5MTRS",
  "COPPER",
  "Copper Wire",
  "Copper Wire Rod 8mm",
  "Corrugated Box",
  "DHAGA",
  "HDPE Compound",
  "IN-PVC",
  "INSU",
  "INSU & OUT",
  "LDPE COMPOUND",
  "MASTER BATCH",
  "Masterbatch Grey",
  "MDPE Compound",
  "OT-PVC",
  "PHLOGOPITE_MICA",
  "PLASTIC CRATE",
  "Plastic Granuals",
  "POLYESTER FILM PANCAKES",
  "POLYESTER FILM TAPE",
  "POLYESTER TAPE",
  "Polyster Yarn",
  "PVC Compound",
  "PVC Master Batch",
  "Spool",
  "SPOOL",
  "TAPE",
  "XL_ZHFR",
  "Other",
] as const;
