export {
  HYBRID_MACHINE_SUPERVISE_ROLES,
  Role,
} from "@/lib/rbac-types";
export type {
  MachineAccessOpts,
  PriceSheetUser,
} from "@/lib/rbac-types";
export {
  canAccessMachineProduction,
  canAdminMachineProduction,
  canAlwaysEditQuadOpeningStock,
  canApproveEntries,
  canCombineMachineSupervise,
  canEnterData,
  canEnterExpenseData,
  canEnterMachineProduction,
  canEnterPurchaseAndSalesOnly,
  canEnterStockData,
  canManageUsers,
  canViewAllPlantEntries,
  canViewFullPnl,
  canViewPnl,
  canViewPriceSheet,
  canViewUsersDirectory,
  getOpeningStockEditorEmail,
  getPrimarySuperAdminEmail,
  hasGlobalPlantAccess,
  hasStockExtraAccess,
  isAccountant,
  isAccountantPnlLimited,
  isAdminOrHead,
  isBusinessHead,
  isMachineSupervisor,
  isMachineSupervisorOnly,
  isPlantManager,
  isPrimarySuperAdmin,
  isStockEntryOnly,
  isSuperAdmin,
  isViewer,
  seesOwnEntriesOnly,
  usesSuperAdminPnlScope,
} from "@/lib/rbac-checks";
export { canAccessPlant, getAccessiblePlantIds } from "@/lib/rbac-plants";
