export const SALE_ALIASES: Record<string, string[]> = {
  date: ["date", "entry date", "sales date"],
  shift: ["shift"],
  customer: [
    "customer name",
    "customer",
    "party name",
    "party",
    "supplier name",
    "supplier",
  ],
  billNumber: [
    "bill number",
    "bill no",
    "invoice no",
    "invoice number",
    "invoice no.",
  ],
  billDate: ["bill date", "invoice date"],
  item: [
    "conductor size",
    "description of goods",
    "item details",
    "item description",
    "item",
    "description",
    "particulars",
    "product",
  ],
  unit: ["unit", "uom"],
  quantity: ["quantity", "qty", "qty nos"],
  qtyMtr: ["qty mtr", "qty-mtr", "quantity mtr"],
  rate: ["rate", "price", "rate rs"],
  salesValue: ["sales value", "goods value", "basic value", "amount"],
  type: ["type", "sale type"],
  notes: ["notes", "remarks", "remark"],
  inMeter: ["in meter", "in metres", "meter"],
};

export const PURCHASE_ALIASES: Record<string, string[]> = {
  date: ["date", "entry date", "purchase date"],
  shift: ["shift"],
  vendor: [
    "vendor s name",
    "vendor name",
    "vendor",
    "supplier name",
    "supplier",
    "party name",
    "party",
  ],
  billNumber: [
    "bill number",
    "bill no",
    "invoice no challan no",
    "invoice no",
    "invoice number",
    "challan no",
  ],
  billDate: ["bill date", "invoice date"],
  item: [
    "item details",
    "description of goods",
    "item description",
    "item",
    "description",
    "particulars",
    "product",
    "raw material",
  ],
  unit: ["unit", "uom"],
  quantity: ["quantity", "qty"],
  debitQuantity: [
    "debit qty",
    "debit quantity",
    "debitquantity",
    "debit nos",
    "debit qty nos",
  ],
  rate: ["rate", "price"],
  gstPercent: ["gst percent", "gst %", "gstpct"],
  gstin: ["gstin gst no", "gstin", "gst no"],
  type: ["type", "purchase type"],
  source: [
    "purchase source",
    "source",
    "purchase from",
    "stock taken from atcl",
  ],
  notes: ["notes", "remarks", "remark"],
};

export const STOCK_ALIASES: Record<string, string[]> = {
  date: ["date", "entry date", "stock date", "as on"],
  shift: ["shift"],
  item: [
    "item",
    "cable",
    "raw material / cable",
    "list of items",
    "particulars",
    "item name",
    "description",
    "product",
  ],
  size: ["size", "conductor size"],
  unit: ["unit", "uom"],
  quantity: [
    "qty",
    "finished qty",
    "issued quantity",
    "closing stock",
    "closing qty",
    "quantity",
  ],
  rate: ["rate", "price", "avg rate"],
  value: ["closing value", "value", "amount"],
  category: ["stock category", "category"],
  stockType: ["stock type"],
  salesKm: ["sales km", "sales"],
  drumLength: ["drum length", "coil length", "drum / coil length"],
  callPutup: ["call putup", "call put-up"],
  putupDate: ["put up date", "putup date", "put-up date"],
  partyName: ["party name", "party", "customer name", "call putup party"],
  dispatchPending: ["dispatch pending", "pending dispatch", "dispatch qty"],
  dispatchParty: ["dispatch party", "dispatch party name"],
  notes: ["notes", "remarks", "remark"],
};

export const EXPENSE_ALIASES: Record<string, string[]> = {
  date: ["payment date", "date", "entry date", "expense date"],
  shift: ["shift"],
  head: [
    "expense head",
    "head",
    "expense type",
    "type",
    "category",
    "nature of expense",
    "nature",
  ],
  nature: ["nature of expense", "nature", "sub nature", "misc nature"],
  description: [
    "description of expense",
    "description",
    "particulars",
    "narration",
    "details",
  ],
  payMode: ["pay mode", "payment mode", "mode", "payment"],
  amount: [
    "factory expense",
    "factory amount",
    "expense amount",
    "amount",
    "value",
  ],
  contractor: ["contractor salary", "contractor", "labour"],
  supervisor: ["supervisor salary", "supervisor"],
  billNumber: ["bill number", "bill no"],
  opening: ["opening reading", "opening"],
  closing: ["closing reading", "closing"],
  vendor: ["vendor", "vendor name", "supplier"],
  cost: ["cost", "asset cost", "basic", "billing price"],
  gst: ["gst amount", "gst"],
  depPercent: [
    "depreciation percent",
    "dep percent",
    "dep %",
    "dep",
    "depreciation",
  ],
  area: ["covered area", "area", "sqft", "covered area sqft"],
  rentRate: ["rent rate", "rate per sqft", "rent rate per sqft"],
};

export const ELECTRICITY_ALIASES: Record<string, string[]> = {
  date: ["months", "month", "date", "entry date"],
  opening: ["opening reading", "opening"],
  closing: ["closing reading", "closing"],
  amount: [
    "electricity fuel power amt",
    "electricity bill amt",
    "electricity bill amount",
    "fuel power amt",
    "bill amt",
    "amount",
    "value",
  ],
  notes: ["notes", "remark", "remarks"],
};

export const RENT_ALIASES: Record<string, string[]> = {
  date: ["months", "month", "date", "entry date"],
  area: ["covered area", "area", "sqft"],
  rentRate: ["rent rate", "rate per sqft"],
  amount: ["rent exp", "rent expense", "amount", "value"],
  rateOnly: ["rate"],
  notes: ["notes", "remark", "remarks"],
};

export const FAR_ALIASES: Record<string, string[]> = {
  date: ["bill date", "date", "entry date"],
  vendor: ["supplier name", "supplier", "vendor", "vendor name"],
  description: [
    "assets description",
    "asset description",
    "description",
    "particulars",
  ],
  billNumber: ["bill number", "bill no"],
  billDate: ["bill date", "invoice date"],
  cost: ["billing price", "cost", "asset cost", "basic"],
  gst: ["gst 18", "gst amount", "gst"],
  depPercent: ["dep %", "dep", "depreciation percent", "depreciation"],
  notes: ["notes", "remarks", "remark"],
};
